### PR TITLE
Added export templates

### LINKED ISSUE #261: Create ITemplate

### LINKED ISSUE #262: Use ApsimXporter 'CreateModel' style methods to implement templates

### PR DESCRIPTION
**Pull request by MikeStower**
Resolves #261
Resolves #262

### CODE REVIEW

**Comment by MikeStower** [comment]
No rush on merging - I was mostly putting it up so you could see what I was working on and get feedback. I'm going to make more changes anyway might be good to keep them all in the same pull request.

**Comment by MikeStower** [comment]
I think I've realised how to approach the Type issue. I was confused because in the examples that I was looking at, the Builder always returns some concrete object. However, in the context of REMS, we can subvert this, because we don't actually *need* the object once the builder has finished creating it - we simply export it immediately.

So my idea is, rather than the builder having some T GetResult() method, we have some void ExportFile() method.

So the builder has a collection of fluent extension methods that accept Templates, which is constructed by some director, e.g.

``` 
public class Director
{
    public IBuilder Construct(IBuilder builder)
    {
        var store = new DataStoreTemplate();
        var weather = new WeatherTemplate();
        var experiment = new ExperimentTemplate()

        builder.AddDataStore(store)
            .AddWeather(weather)
            .AddExperiment(experiment)
    }
}

public class ApsimXBuilder : IBuilder
{
    public IBuilder AddDataStore(ITemplate template) {...}
    public IBuilder AddWeather(ITemplate template) {...}
    public IBuilder AddExperiment(ITemplate template) {...}

    public void Export(string path) {...}
}
```

This way, any and all references to APSIM models can be completely constrained to the ApsimXBuilder class.

**Comment by jbrider** [comment]
Looking at that implementation do we need to have AddDataStore, AddWeather as separate functions at all?
If the interface is ITemplate, then do the templates need to be given their own function?

**Comment by jbrider** [comment]
You can use just an AddTemplate(ITemplate).
The type is still an issue though - but it can be contained within the builder.
Or cleaner again is that the builder has a wrapper object for the type - just to decouple the builder from the template.

**Comment by MikeStower** [comment]
I had the different AddTemplate functions listed separately because I was picturing different implementations in the builder, but looking back on it I'm sensing a bit of code smell. 

I'm starting to think this whole approach / pattern might not be be appropriate to the situation. I'm trying to create an interface that describes a template without referencing APSIM models, but the only thing any of the templates have in common is that they *are* APSIM models. I feel that conceptually the ideas themselves are too tightly coupled to break apart in the way that this pattern suggests.

**Comment by jbrider** [comment]
The templates are similar to Model within nextgen.
The builder is a method for calling/managing them.
The objects within the builder are called sequentially to build a file.
1 of the files is an xml file, the other file is a json file - but can also be managed through model classes.

The data needed for the different file types is going to be similar for each template type - so a met template is going to be very similar in it's logic/structure for both classic and nextgen - as the diff between them is actually how that data is saved to file...
this lends itself to a strategy pattern - where the template's write method/class needs to know about it's destination format, and about the template it gets data from. So you could create a MetTemplateApsimX implementation of an IOutputWriter class maybe. So each template has an IOutputWriter class - that can be passed into the next ITemplate - that way the builder is decoupled, the templates are common for the input data, and the output implementation only knows about it's template and output type... some coupling which is necessary somewhere.

This is much easier on a whiteboard.
I agree it doesn't fit the format we originally talked about - I am not surprised these things change once you start to think about implementation.

**Pull request closed without merging**
