### PR TITLE
Tidied up soil chart

### LINKED ISSUE #198: Soil chart needs tidying up
- Series points need to be connected vertically not horizontally
- x-axis bounds must be set dependent on the data
- Traits need more obvious descriptions
- Title needs to be included

### PR DESCRIPTION
**Pull request by MikeStower**
Resolves #198

### CODE REVIEW

**Comment by jbrider** [comment]
What is a ListPair?

**Comment by MikeStower** [comment]
It's used to display the trait description next to the trait name in a ListBox. There was some existing functionality that assumed the objects in the ListBox were strings of trait names, so I couldn't just attach the descriptions. ListPair uses the ToString override to display the joint name + description, but stores them separately so I can easily pull out the trait names where I need to.

**Comment by jbrider** [comment]
So it should have some sort of comment to reflect then?

**Comment by MikeStower** [comment]
Good point, I might also change the name to something like ListTrait, since thats more specific to its purpose.

**Pull request merged**
