### PR TITLE
ApsimX export improvements

### LINKED ISSUE #208: Exported simulations should be runnable

### PR DESCRIPTION
**Pull request by MikeStower**
Resolves #208

### CODE REVIEW

**Comment by jbrider** [comment]
Irrigation from experiments is usually a set amount on a set date - the script seems overly complex?
Did you find an example of an operations component to use.

**Comment by MikeStower** [comment]
Yeah - this script is just copy-pasted from an example I found. I'll see if I can find a simpler one, though.

**Comment by MikeStower** [comment]
Additionally, this script is only used when irrigation is a Factor of the experiment. It is not included in the export by default. The normal handling of irrigation is to replace the operations component through a composite factor, i.e,

image

**Comment by jbrider** [comment]
Use the sorghum.apsimx file - The hermitage simulations are basically how they should come out of Rems.

**Pull request merged**
