### PR TITLE
Reworked importer node tree to better visualise types of data being imported

### LINKED ISSUE #130: Importer node tree needs to be refined
Areas to be improved:

- Error messages (more clarity, user friendly language)
- Icons (greater diversity, better indication of what they represent)
- Node organisation (Add another layer of subnodes to group columns based on import status)

### PR DESCRIPTION
**Pull request by MikeStower**
Instead of having a two layer tree with tables and column nodes, and intermediary layer of 'group' nodes that sort the columns based on their type has been introduced. The goal is to make it more clear to the user which action they need to take to validate the data prior to import.

Resolves #130

### CODE REVIEW

**Comment by jbrider** [comment]
It says that is a Draft and cannot be merged yet?

**Comment by MikeStower** [comment]
> It says that is a Draft and cannot be merged yet?

Yeah, it's a fairly substantive change to the layout of the nodes in the import tree, so I thought it would be best to get feedback / make adjustments before commiting it to master, so I marked this pull as a draft. I'm about to finish publishing the setup file using this branch, so you & Greg can look at it first.

**Comment by MikeStower** [comment]
Resolves #137

**Comment by MikeStower** [comment]
@jbrider Regarding #136, would it be better to call it information rather than properties? I feel like property is a 'developer' name for the data type - it's hard to succinctly describe *what* it's a property of. But by calling it 'Information' we can instead distinguish between 'information about the experiment' and 'trait data'.

**Comment by jbrider** [comment]
The main issue is that you are representing data the program expects/requires vs data it didn't expect.
The user will most likely only understand that it they have columns of data in a spreadsheet - which you are showing in the table.  The thing you are wanting the user to understand is that some columns are expected/required by the import process - which should show up as missing or an error.
Anything else is then unexpected data and the question really is: is it supposed to be one of the required columns (property) and if not - do we want to save it in the database (as a Trait) or just ignore it.

**Comment by MikeStower** [comment]
Then my idea would be to call it 'Information' and include nodes for all the properties, perhaps separated further into 'required' and 'additional', because some of the data (like notes) are not essential for importing successfully. The nodes would display an icon based on whether or not that property has found a matching column. Similar to how right clicking an unknown node lets you add it as a property, clicking on one of these nodes might give you the option to match it to one of the unknowns.

Framing it like this makes it explicit that some types of data are required for the import process.

**Pull request merged**
